#ifndef OPENGL_RAYTRACER_CONSTANTS_H
#define OPENGL_RAYTRACER_CONSTANTS_H

#define VERTEX_SSBO_BINDING 0
#define TRIANGLE_SSBO_BINDING 1
#define TRIANGLE_NORMAL_SSBO_BINDING 2
#define PIXEL_OUTPUT_BINDING 3

const float FOV = 90.0f;
const float VIEWPORT_DIST = 1.0f;
const unsigned int RAY_BOUNCES = 5;
const unsigned int RAYS_PER_PIXEL = 5;

#endif //OPENGL_RAYTRACER_CONSTANTS_H
